App Structure
SkynetLabs/skyblog pull request #8
Opened 2021-08-19 02:58 UTC by kevin-carlson

Basic app structure created. Files added:

1. components/NavigationBar.js - basic navigation bar
2. pages/Blog.js - page used for viewing of blogs
3. pages/Create.js - create blog page with title and subtitle inputs
4. pages/Home.js - home page with basic information and login/get started button
5. pages/Profile.js - initialize file for user profiles

Edited App.js with basic page routing.

2021-08-19 21:32 UTC, dghelm commented on src/App.js
> +import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
You'll want to change "BrowserRouter" to "HashRouter" for Skynet Deployments. (At least until our support for this rolls out in the next couple of weeks.)

2021-08-19 21:32 UTC, dghelm commented on src/pages/Home.js
> +          onClick={openSkynetHomePage}
I think for a link you might just want to stick with the props ` target="_blank" href="https://siasky.net/"`

2021-08-20 12:56 UTC, MSevey requested changes

2021-08-20 12:56 UTC, MSevey commented on src/pages/Home.js
> +export default function Home(props) {
REQ: comment explaining purpose of the function

2021-08-20 12:56 UTC, MSevey commented on src/pages/Create.js
> +export default function Create(props) {
REQ: comment explaining purpose of the function

2021-08-20 12:56 UTC, MSevey commented on src/pages/Blog.js
> +export default function Blog(props) {
REQ: comment explaining purpose of the function

2021-08-20 12:56 UTC, MSevey commented on src/components/NavigationBar.js
> +export default function NavigationBar(props) {
REQ: comment explaining purpose of the function

2021-08-20 12:56 UTC, MSevey commented on src/components/NavigationBar.js
> +const useStyles = makeStyles((theme) => ({
REQ: comment explaining what/why you are defining here

2021-08-20 12:56 UTC, MSevey commented on src/App.js
> +const theme = createTheme({
REQ: comment explaining what this const is.

2021-08-20 12:56 UTC, MSevey commented on src/App.js
> +const themeDark = createTheme({
REQ: comment explaining what this const is.

2021-08-24 13:56 UTC, merged